name: TFLint

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]
  push:
    

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v1
      
      - name: Run TFLint with Reviewdog
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: info
          reporter: github-pr-review # Change reporter.
          filter_mode: file # Change filter mode.
          tflint_version: 'v0.50.0'
          tflint_config: .tflint.hcl
